services:
  ingestion:
    build: ./src/services/ingestion
    ports:
      - "8080:8080"
    restart: unless-stopped
    container_name: ingestion
    env_file:
      - .env
    environment:
      - DB_HOST=timescaledb
    depends_on:
      timescaledb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - city-flow

  frontend:
    build: ./src/frontend
    container_name: frontend
    ports:
      - "4000:4000"
    restart: unless-stopped
    networks:
      - city-flow

  mosquitto:
    build: ./src/mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    restart: unless-stopped
    networks:
      - city-flow

  timescaledb:
    image: postgres:14
    container_name: timescaledb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - city-flow

  subscriber:
    build: ./src/iot-simulator
    container_name: subscriber
    env_file:
      - .env
    environment:
      - DB_HOST=timescaledb
      - MQTT_BROKER=mosquitto
    depends_on:
      timescaledb:
        condition: service_healthy
      mosquitto:
        condition: service_started
    restart: unless-stopped
    networks:
      - city-flow

  sensor1:
    build: ./src/iot-simulator
    container_name: sensor1
    command: ["python", "sensor1.py"]
    env_file:
      - .env
    depends_on:
      - mosquitto
    restart: unless-stopped

  sensor2:
    build: ./src/iot-simulator
    container_name: sensor2
    command: ["python", "sensor2.py"]
    env_file:
      - .env
    depends_on:
      - mosquitto
    restart: unless-stopped

  sensor3:
    build: ./src/iot-simulator
    container_name: sensor3
    command: ["python", "sensor3.py"]
    env_file:
      - .env
    depends_on:
      - mosquitto
    restart: unless-stopped

  sensor4:
    build: ./src/iot-simulator
    container_name: sensor4
    command: ["python", "sensor4.py"]
    env_file:
      - .env
    depends_on:
      - mosquitto
    restart: unless-stopped

  sensor5:
    build: ./src/iot-simulator
    container_name: sensor5
    command: ["python", "sensor5.py"]
    env_file:
      - .env
    depends_on:
      - mosquitto
    restart: unless-stopped

  sensor6:
    build: ./src/iot-simulator
    container_name: sensor6
    command: ["python", "sensor6.py"]
    env_file:
      - .env
    environment:
      - MQTT_BROKER=mosquitto
    depends_on:
      mosquitto:
        condition: service_started
    restart: unless-stopped
    networks:
      - city-flow

volumes:
  timescaledb-data:

networks:
  city-flow:
    driver: bridge
